AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: true
  Max: 15

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets
