name: Ruby

on:
  push:
    branches:
      - main
    paths:
      - 'lib/**'
      - 'spec/**'
      - 'Gemfile'
      - 'shrine-thumbhash.gemspec'

  pull_request:
    paths:
      - 'lib/**'
      - 'spec/**'
      - 'Gemfile'
      - 'shrine-thumbhash.gemspec'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}, Shrine ${{ matrix.shrine }}
    strategy:
      matrix:
        ruby:
          - '2.6'
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
        shrine:
          - '3.3'
          - '3.4'
        include:
          - ruby: '2.6'
            shrine: '3.0'
          - ruby: '2.7'
            shrine: '3.0'
          - ruby: '2.6'
            shrine: '3.1'
          - ruby: '2.7'
            shrine: '3.1'
          - ruby: '2.6'
            shrine: '3.2'
          - ruby: '2.7'
            shrine: '3.2'

    steps:
    - uses: actions/checkout@v3
    - run: sudo apt install --no-install-recommends --no-install-suggests -y libvips-dev
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
        cache-version: shrine-${{ matrix.shrine }}
      env:
        SHRINE_VERSION: ${{ matrix.shrine }}
    - name: Run the default task
      run: bundle exec rake
